spring:
  application:
    name: ms-admin-registry-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
