
server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls-primary-name: ms-seguridad
    urls:
      - name: ms-seguridad
        url: /ms-seguridad/v3/api-docs
      - name: ms-gestion-instructor
        url: /ms-gestion-instructor/v3/api-docs
      - name: ms-gestion-alumno
        url: /ms-gestion-alumno/v3/api-docs
      - name: ms-gestion-taller
        url: /ms-gestion-taller/v3/api-docs
