# ============================================================
# Configuracion del microservicio de ALUMNOS
# ============================================================
server:
  port: 8082

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/db_alumno?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
